-- MySQL Script generated by MySQL Workbench
-- 11/04/16 20:44:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Airplane`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airplane` (
  `idAirplane` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `length` INT NOT NULL,
  `span` INT NOT NULL,
  `passenger_count` INT NOT NULL,
  `engine` VARCHAR(45) NOT NULL,
  `engine_count` INT NOT NULL,
  PRIMARY KEY (`idAirplane`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airline` (
  `idAirline` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `airplane_number` INT NOT NULL,
  PRIMARY KEY (`idAirline`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pilot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pilot` (
  `idPilot` INT NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  `flight_time` INT NOT NULL,
  PRIMARY KEY (`idPilot`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Flight` (
  `idFlight` INT NOT NULL,
  `Airplane_idAirplane` INT NOT NULL,
  `Airline_idAirline` INT NOT NULL,
  `Pilot_idPilot` INT NOT NULL,
  `place_takeoff` VARCHAR(45) NOT NULL,
  `place_landing` VARCHAR(45) NOT NULL,
  `time_takeoff` DATE NOT NULL,
  `time_landing` DATE NOT NULL,
  PRIMARY KEY (`idFlight`, `Airplane_idAirplane`, `Airline_idAirline`, `Pilot_idPilot`),
  INDEX `fk_Flight_Airplane_idx` (`Airplane_idAirplane` ASC),
  INDEX `fk_Flight_Airline1_idx` (`Airline_idAirline` ASC),
  INDEX `fk_Flight_Pilot1_idx` (`Pilot_idPilot` ASC),
  CONSTRAINT `fk_Flight_Airplane`
    FOREIGN KEY (`Airplane_idAirplane`)
    REFERENCES `mydb`.`Airplane` (`idAirplane`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_Airline1`
    FOREIGN KEY (`Airline_idAirline`)
    REFERENCES `mydb`.`Airline` (`idAirline`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_Pilot1`
    FOREIGN KEY (`Pilot_idPilot`)
    REFERENCES `mydb`.`Pilot` (`idPilot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
